from __future__ import annotations

import re
from datetime import timedelta
from enum import Enum, StrEnum
from typing import Literal, get_args

EVENT_LISTENERS_TIMEOUT = timedelta(seconds=5)

BASE64_REGEXP = '[-A-Za-z0-9+/]*={0,3}'
ENCRYPTED_STRING_VALUE_PREFIX = 'ENCRYPTED_VALUE'
ENCRYPTED_JSON_VALUE_PREFIX = 'ENCRYPTED_JSON'
ENCRYPTED_INPUT_VALUE_REGEXP = re.compile(
    f'^({ENCRYPTED_STRING_VALUE_PREFIX}|{ENCRYPTED_JSON_VALUE_PREFIX}):(?:({BASE64_REGEXP}):)?({BASE64_REGEXP}):({BASE64_REGEXP})$'
)


class ActorEventTypes(StrEnum):
    """Event types that can be sent to Actors during execution."""

    SYSTEM_INFO = 'systemInfo'
    MIGRATING = 'migrating'
    PERSIST_STATE = 'persistState'
    ABORTING = 'aborting'


class ActorEnvVars(StrEnum):
    """Environment variables with ACTOR_ prefix set by the Apify platform."""

    BUILD_ID = 'ACTOR_BUILD_ID'
    BUILD_NUMBER = 'ACTOR_BUILD_NUMBER'
    BUILD_TAGS = 'ACTOR_BUILD_TAGS'
    DEFAULT_DATASET_ID = 'ACTOR_DEFAULT_DATASET_ID'
    DEFAULT_KEY_VALUE_STORE_ID = 'ACTOR_DEFAULT_KEY_VALUE_STORE_ID'
    DEFAULT_REQUEST_QUEUE_ID = 'ACTOR_DEFAULT_REQUEST_QUEUE_ID'
    EVENTS_WEBSOCKET_URL = 'ACTOR_EVENTS_WEBSOCKET_URL'
    FULL_NAME = 'ACTOR_FULL_NAME'
    ID = 'ACTOR_ID'
    INPUT_KEY = 'ACTOR_INPUT_KEY'
    MAX_PAID_DATASET_ITEMS = 'ACTOR_MAX_PAID_DATASET_ITEMS'
    MAX_TOTAL_CHARGE_USD = 'ACTOR_MAX_TOTAL_CHARGE_USD'
    MEMORY_MBYTES = 'ACTOR_MEMORY_MBYTES'
    PERMISSION_LEVEL = 'ACTOR_PERMISSION_LEVEL'
    RUN_ID = 'ACTOR_RUN_ID'
    STANDBY_PORT = 'ACTOR_STANDBY_PORT'
    STANDBY_URL = 'ACTOR_STANDBY_URL'
    STARTED_AT = 'ACTOR_STARTED_AT'
    TASK_ID = 'ACTOR_TASK_ID'
    TIMEOUT_AT = 'ACTOR_TIMEOUT_AT'
    WEB_SERVER_PORT = 'ACTOR_WEB_SERVER_PORT'
    WEB_SERVER_URL = 'ACTOR_WEB_SERVER_URL'


class ApifyEnvVars(StrEnum):
    """Environment variables with APIFY_ prefix set by the Apify platform."""

    API_BASE_URL = 'APIFY_API_BASE_URL'
    API_PUBLIC_BASE_URL = 'APIFY_API_PUBLIC_BASE_URL'
    DEDICATED_CPUS = 'APIFY_DEDICATED_CPUS'
    DEFAULT_BROWSER_PATH = 'APIFY_DEFAULT_BROWSER_PATH'
    DISABLE_BROWSER_SANDBOX = 'APIFY_DISABLE_BROWSER_SANDBOX'
    DISABLE_OUTDATED_WARNING = 'APIFY_DISABLE_OUTDATED_WARNING'
    FACT = 'APIFY_FACT'
    HEADLESS = 'APIFY_HEADLESS'
    INPUT_SECRETS_PRIVATE_KEY_FILE = 'APIFY_INPUT_SECRETS_PRIVATE_KEY_FILE'
    INPUT_SECRETS_PRIVATE_KEY_PASSPHRASE = 'APIFY_INPUT_SECRETS_PRIVATE_KEY_PASSPHRASE'
    IS_AT_HOME = 'APIFY_IS_AT_HOME'
    LOCAL_STORAGE_DIR = 'APIFY_LOCAL_STORAGE_DIR'
    LOG_FORMAT = 'APIFY_LOG_FORMAT'
    LOG_LEVEL = 'APIFY_LOG_LEVEL'
    MAX_USED_CPU_RATIO = 'APIFY_MAX_USED_CPU_RATIO'
    META_ORIGIN = 'APIFY_META_ORIGIN'
    METAMORPH_AFTER_SLEEP_MILLIS = 'APIFY_METAMORPH_AFTER_SLEEP_MILLIS'
    PERSIST_STATE_INTERVAL_MILLIS = 'APIFY_PERSIST_STATE_INTERVAL_MILLIS'
    PERSIST_STORAGE = 'APIFY_PERSIST_STORAGE'
    PROXY_HOSTNAME = 'APIFY_PROXY_HOSTNAME'
    PROXY_PASSWORD = 'APIFY_PROXY_PASSWORD'
    PROXY_PORT = 'APIFY_PROXY_PORT'
    PROXY_STATUS_URL = 'APIFY_PROXY_STATUS_URL'
    PURGE_ON_START = 'APIFY_PURGE_ON_START'
    SDK_LATEST_VERSION = 'APIFY_SDK_LATEST_VERSION'
    SYSTEM_INFO_INTERVAL_MILLIS = 'APIFY_SYSTEM_INFO_INTERVAL_MILLIS'
    TOKEN = 'APIFY_TOKEN'
    USER_ID = 'APIFY_USER_ID'
    USER_IS_PAYING = 'APIFY_USER_IS_PAYING'
    WORKFLOW_KEY = 'APIFY_WORKFLOW_KEY'


class ActorExitCodes(int, Enum):
    """Standard exit codes used by Actors to indicate run completion status."""

    SUCCESS = 0
    ERROR_USER_FUNCTION_THREW = 91


# Environment variable type classification lists.

INTEGER_ENV_VARS_TYPE = Literal[
    ActorEnvVars.MAX_PAID_DATASET_ITEMS,
    ActorEnvVars.MEMORY_MBYTES,
    ActorEnvVars.STANDBY_PORT,
    ActorEnvVars.WEB_SERVER_PORT,
    ApifyEnvVars.DEDICATED_CPUS,
    ApifyEnvVars.LOG_LEVEL,
    ApifyEnvVars.METAMORPH_AFTER_SLEEP_MILLIS,
    ApifyEnvVars.PERSIST_STATE_INTERVAL_MILLIS,
    ApifyEnvVars.PROXY_PORT,
    ApifyEnvVars.SYSTEM_INFO_INTERVAL_MILLIS,
]

INTEGER_ENV_VARS: list[INTEGER_ENV_VARS_TYPE] = list(get_args(INTEGER_ENV_VARS_TYPE))

FLOAT_ENV_VARS_TYPE = Literal[
    ActorEnvVars.MAX_TOTAL_CHARGE_USD,
    ApifyEnvVars.MAX_USED_CPU_RATIO,
]

FLOAT_ENV_VARS: list[FLOAT_ENV_VARS_TYPE] = list(get_args(FLOAT_ENV_VARS_TYPE))

BOOL_ENV_VARS_TYPE = Literal[
    ApifyEnvVars.DISABLE_BROWSER_SANDBOX,
    ApifyEnvVars.DISABLE_OUTDATED_WARNING,
    ApifyEnvVars.HEADLESS,
    ApifyEnvVars.IS_AT_HOME,
    ApifyEnvVars.PERSIST_STORAGE,
    ApifyEnvVars.PURGE_ON_START,
    ApifyEnvVars.USER_IS_PAYING,
]

BOOL_ENV_VARS: list[BOOL_ENV_VARS_TYPE] = list(get_args(BOOL_ENV_VARS_TYPE))

DATETIME_ENV_VARS_TYPE = Literal[
    ActorEnvVars.STARTED_AT,
    ActorEnvVars.TIMEOUT_AT,
]

DATETIME_ENV_VARS: list[DATETIME_ENV_VARS_TYPE] = list(get_args(DATETIME_ENV_VARS_TYPE))

STRING_ENV_VARS_TYPE = Literal[
    ActorEnvVars.BUILD_ID,
    ActorEnvVars.BUILD_NUMBER,
    ActorEnvVars.DEFAULT_DATASET_ID,
    ActorEnvVars.DEFAULT_KEY_VALUE_STORE_ID,
    ActorEnvVars.DEFAULT_REQUEST_QUEUE_ID,
    ActorEnvVars.EVENTS_WEBSOCKET_URL,
    ActorEnvVars.FULL_NAME,
    ActorEnvVars.ID,
    ActorEnvVars.INPUT_KEY,
    ActorEnvVars.PERMISSION_LEVEL,
    ActorEnvVars.RUN_ID,
    ActorEnvVars.STANDBY_URL,
    ActorEnvVars.TASK_ID,
    ActorEnvVars.WEB_SERVER_URL,
    ApifyEnvVars.API_BASE_URL,
    ApifyEnvVars.API_PUBLIC_BASE_URL,
    ApifyEnvVars.DEFAULT_BROWSER_PATH,
    ApifyEnvVars.FACT,
    ApifyEnvVars.INPUT_SECRETS_PRIVATE_KEY_FILE,
    ApifyEnvVars.INPUT_SECRETS_PRIVATE_KEY_PASSPHRASE,
    ApifyEnvVars.LOCAL_STORAGE_DIR,
    ApifyEnvVars.LOG_FORMAT,
    ApifyEnvVars.META_ORIGIN,
    ApifyEnvVars.PROXY_HOSTNAME,
    ApifyEnvVars.PROXY_PASSWORD,
    ApifyEnvVars.PROXY_STATUS_URL,
    ApifyEnvVars.SDK_LATEST_VERSION,
    ApifyEnvVars.TOKEN,
    ApifyEnvVars.USER_ID,
    ApifyEnvVars.WORKFLOW_KEY,
]

STRING_ENV_VARS: list[STRING_ENV_VARS_TYPE] = list(get_args(STRING_ENV_VARS_TYPE))

COMMA_SEPARATED_LIST_ENV_VARS_TYPE = Literal[ActorEnvVars.BUILD_TAGS]

COMMA_SEPARATED_LIST_ENV_VARS: list[COMMA_SEPARATED_LIST_ENV_VARS_TYPE] = list(
    get_args(COMMA_SEPARATED_LIST_ENV_VARS_TYPE)
)
