from __future__ import annotations

import re
from datetime import timedelta
from enum import Enum, StrEnum

EVENT_LISTENERS_TIMEOUT = timedelta(seconds=5)
"""Timeout for waiting on event listeners to finish during Actor exit."""

ENCRYPTED_STRING_VALUE_PREFIX = 'ENCRYPTED_VALUE'
"""Prefix for encrypted string values in Actor input."""

ENCRYPTED_JSON_VALUE_PREFIX = 'ENCRYPTED_JSON'
"""Prefix for encrypted JSON values in Actor input."""

ENCRYPTED_INPUT_VALUE_REGEXP = re.compile(
    r'^(ENCRYPTED_VALUE|ENCRYPTED_JSON):(?:([-A-Za-z0-9+/]*={0,3}):)?([-A-Za-z0-9+/]*={0,3}):([-A-Za-z0-9+/]*={0,3})$'
)
"""Regex matching encrypted input values with base64-encoded components."""


class ActorEnvVars(StrEnum):
    """Environment variables with ACTOR_ prefix set by the Apify platform."""

    BUILD_ID = 'ACTOR_BUILD_ID'
    BUILD_NUMBER = 'ACTOR_BUILD_NUMBER'
    BUILD_TAGS = 'ACTOR_BUILD_TAGS'
    DEFAULT_DATASET_ID = 'ACTOR_DEFAULT_DATASET_ID'
    DEFAULT_KEY_VALUE_STORE_ID = 'ACTOR_DEFAULT_KEY_VALUE_STORE_ID'
    DEFAULT_REQUEST_QUEUE_ID = 'ACTOR_DEFAULT_REQUEST_QUEUE_ID'
    EVENTS_WEBSOCKET_URL = 'ACTOR_EVENTS_WEBSOCKET_URL'
    FULL_NAME = 'ACTOR_FULL_NAME'
    ID = 'ACTOR_ID'
    INPUT_KEY = 'ACTOR_INPUT_KEY'
    MAX_PAID_DATASET_ITEMS = 'ACTOR_MAX_PAID_DATASET_ITEMS'
    MAX_TOTAL_CHARGE_USD = 'ACTOR_MAX_TOTAL_CHARGE_USD'
    MEMORY_MBYTES = 'ACTOR_MEMORY_MBYTES'
    PERMISSION_LEVEL = 'ACTOR_PERMISSION_LEVEL'
    RUN_ID = 'ACTOR_RUN_ID'
    STANDBY_PORT = 'ACTOR_STANDBY_PORT'
    STANDBY_URL = 'ACTOR_STANDBY_URL'
    STARTED_AT = 'ACTOR_STARTED_AT'
    TASK_ID = 'ACTOR_TASK_ID'
    TIMEOUT_AT = 'ACTOR_TIMEOUT_AT'
    WEB_SERVER_PORT = 'ACTOR_WEB_SERVER_PORT'
    WEB_SERVER_URL = 'ACTOR_WEB_SERVER_URL'


class ApifyEnvVars(StrEnum):
    """Environment variables with APIFY_ prefix set by the Apify platform."""

    API_BASE_URL = 'APIFY_API_BASE_URL'
    API_PUBLIC_BASE_URL = 'APIFY_API_PUBLIC_BASE_URL'
    DEDICATED_CPUS = 'APIFY_DEDICATED_CPUS'
    DEFAULT_BROWSER_PATH = 'APIFY_DEFAULT_BROWSER_PATH'
    DISABLE_BROWSER_SANDBOX = 'APIFY_DISABLE_BROWSER_SANDBOX'
    DISABLE_OUTDATED_WARNING = 'APIFY_DISABLE_OUTDATED_WARNING'
    FACT = 'APIFY_FACT'
    HEADLESS = 'APIFY_HEADLESS'
    INPUT_SECRETS_PRIVATE_KEY_FILE = 'APIFY_INPUT_SECRETS_PRIVATE_KEY_FILE'
    INPUT_SECRETS_PRIVATE_KEY_PASSPHRASE = 'APIFY_INPUT_SECRETS_PRIVATE_KEY_PASSPHRASE'
    IS_AT_HOME = 'APIFY_IS_AT_HOME'
    LOCAL_STORAGE_DIR = 'APIFY_LOCAL_STORAGE_DIR'
    LOG_FORMAT = 'APIFY_LOG_FORMAT'
    LOG_LEVEL = 'APIFY_LOG_LEVEL'
    MAX_USED_CPU_RATIO = 'APIFY_MAX_USED_CPU_RATIO'
    META_ORIGIN = 'APIFY_META_ORIGIN'
    METAMORPH_AFTER_SLEEP_MILLIS = 'APIFY_METAMORPH_AFTER_SLEEP_MILLIS'
    PERSIST_STATE_INTERVAL_MILLIS = 'APIFY_PERSIST_STATE_INTERVAL_MILLIS'
    PERSIST_STORAGE = 'APIFY_PERSIST_STORAGE'
    PROXY_HOSTNAME = 'APIFY_PROXY_HOSTNAME'
    PROXY_PASSWORD = 'APIFY_PROXY_PASSWORD'
    PROXY_PORT = 'APIFY_PROXY_PORT'
    PROXY_STATUS_URL = 'APIFY_PROXY_STATUS_URL'
    PURGE_ON_START = 'APIFY_PURGE_ON_START'
    SDK_LATEST_VERSION = 'APIFY_SDK_LATEST_VERSION'
    SYSTEM_INFO_INTERVAL_MILLIS = 'APIFY_SYSTEM_INFO_INTERVAL_MILLIS'
    TOKEN = 'APIFY_TOKEN'
    USER_ID = 'APIFY_USER_ID'
    USER_IS_PAYING = 'APIFY_USER_IS_PAYING'
    WORKFLOW_KEY = 'APIFY_WORKFLOW_KEY'


class ActorExitCodes(int, Enum):
    """Standard exit codes used by Actors to indicate run completion status."""

    SUCCESS = 0
    ERROR_USER_FUNCTION_THREW = 91
