module.exports = {
    sidebar: [
        {
            type: 'category',
            label: 'Overview',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: '01-overview',
                },
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: '02-guides',
                },
            ],
        },
        {
            type: 'category',
            label: 'Usage concepts',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: '03-concepts',
                },
            ],
        },
        {
            type: 'doc',
            id: 'changelog',
        },
    ],
};
