module.exports = {
  sidebar: [
      {
          type: 'category',
          label: 'Guides',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'guides',
              },
          ],
      },
      {
          type: 'category',
          label: 'Examples',
          items: [
              {
                  type: 'autogenerated',
                  dirName: 'examples',
              },
          ],
      },
      {
          type: 'doc',
          id: 'changelog',
      },
  ],
};
