name: Package check

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  package_check:
    name: Package check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.14"

      - name: Build sdist and wheel
        run: uv run poe build

      - name: Verify built package
        uses: apify/workflows/python-package-check@main
        with:
          package_name: apify
