name: Version conflict check

on:
  workflow_call:

env:
  PYTHON_VERSION: 3.12

jobs:
  check_version_conflict:
    name: Version conflict check
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.title, 'docs:'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pipx install --python ${{ env.PYTHON_VERSION }} poetry
          make install-dev

      - name: Run version conflict check
        run: make check-version-conflict
