name: Update new issue

on:
  workflow_call:

jobs:
  label_issues:
    name: Label issues
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Add the "t-tooling" label to all new issues
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["t-tooling"]
            })
